### ISSUE TITLE
id3 file format

### ISSUE THREAD

**Issue by vasudevavarun** [dusterio/hlsinjector#2]
Hi,
I'm not able to get around the actual format needed for -e option, Can you provide some sample file?

**Comment by dusterio** [comment]
It's in the following format:
{second(s) from the start} plaintext {tag value}

or:
{second(s) from the start} id3 {filename of the ID3 file}

So one line for each injected tag, eg:

5 plaintext My first text
15 plaintext My second message

**Comment by vasudevavarun** [comment]
How can I create .id3 file?

**Comment by dusterio** [comment]
Using any ID3 tool, eg. id3tool in Linux

**Comment by vasudevavarun** [comment]
Thanks sorted

**Comment by praneet195** [comment]
Hi @vasudevavarun can u help me with this? im strugling with the id3 file creation
